create table sales_invoice (
    id bigint generated by default as identity primary key,
    external_id varchar(255),
    invoice_number varchar(255) not null,
    issue_date date,
    sale_date date,
    contractor_name varchar(255),
    net_amount decimal(19, 2),
    gross_amount decimal(19, 2),
    currency varchar(32),
    status varchar(128),
    raw_json clob,
    updated_at timestamp not null
);

create index idx_sales_invoice_issue_date on sales_invoice (issue_date);
create index idx_sales_invoice_updated_at on sales_invoice (updated_at);
create index idx_sales_invoice_number on sales_invoice (invoice_number);
create index idx_sales_invoice_contractor on sales_invoice (contractor_name);
