create table ai_query_history (
    id bigint generated by default as identity primary key,
    prompt clob not null,
    generated_sql clob,
    visualization clob,
    title varchar(255),
    explanation varchar(1000),
    row_count integer,
    status varchar(32) not null,
    sanitized_error_message varchar(2000),
    openai_duration_ms bigint,
    sql_duration_ms bigint,
    created_at timestamp not null
);

create index idx_ai_query_history_created_at on ai_query_history (created_at desc);
create index idx_ai_query_history_status on ai_query_history (status);
